# Generated by Django 5.0.2 on 2024-02-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-votes_ratio']},
        ),
    ]
